#Version contextualizadora.
version: '3.8'
services:
    backend:
        build:
            context: ./backend
        ports:
            - '5000:5000'
        env_file:
            - ./backend/.env.production
        depends_on:
            - postgres
    frontend:
        build:
            context: ./frontend
        ports:
            - '3000:3000'
        env_file:
            - ./frontend/.env
    postgres:
        image: postgres
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
            POSTGRES_DB: mydb
        ports:
            - '5432:5432'
        volumes:
            - pgdata:/var/lib/postgresql/data
volumes:
    pgdata:
